package com.denzelawuah.thesaurus.favouriteWords;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "favouriteWords")
public class FavouriteWord {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;
	
	
	@DynamoDBAttribute
	private String favouriteWord;
	
	@DynamoDBIgnore
	private String httpMethod;
		
	public FavouriteWord () {
		
	}
	
	
	public FavouriteWord(String id, String favouriteWord, String httpMethod) {
		super();
		this.id = id;
		this.favouriteWord = favouriteWord;
		this.httpMethod = httpMethod;
	}




	public String getId() {
		return id;
	}


	public void setId(String id) {
		this.id = id;
	}


	public String getFavouriteWord() {
		return favouriteWord;
	}


	public void setFavouriteWord(String favouriteWord) {
		this.favouriteWord = favouriteWord;
	}


	public String getHttpMethod() {
		return httpMethod;
	}


	public void setHttpMethod(String httpMethod) {
		this.httpMethod = httpMethod;
	}



	@Override
	public String toString() {
		return "FavouriteWord [id=" + id + ", favouriteWord=" + favouriteWord + ", httpMethod=" + httpMethod + "]";
	}

	


}
